# This is a TOML document.
# For information on TOML documents and how to write them visit
# https://en.wikipedia.org/wiki/TOML
# https://github.com/toml-lang/toml

# App options

local_timezone = 'America/Los_Angeles'

input_path = './input'
app_log_path = './logs'
app_log_filename = 'app.log'
refresh_per_second = 1
main_loop_throttle = 0.1

ip_address_nl_del_file = "./IP_ADDESSES_TO_PING.txt"

ip_addresses = [
    '192.168.1.1',
    '192.168.1.3',
    'www.google.com'
]

# Logging Options
[loggers]
# Available options:
# level: 'CRITICAL', 'FATAL', 'ERROR', 'WARN', 'WARNING', 'INFO', 'DEBUG'
# format: https://docs.python.org/3/howto/logging.html#formatters
    [loggers.console]
        level = "DEBUG"
        format = '%(levelname)s - %(module)s - %(message)s'

    [loggers.file]
        level = "DEBUG"
        format = "%(asctime)s - %(module)s - %(levelname)s - %(message)s"

    [loggers.rotating_file]
        # second (s), minute (m), hour (h), day (d)
        level = "DEBUG"
        format = "%(asctime)s - %(module)s - %(levelname)s - %(message)s"
        when = "d"
        interval = 1
        backupCount = 14
